server:
  port: 9000   # API Gateway will run on 9000

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      routes:
        - id: order-service
          uri: lb://ORDERS
          predicates:
            - Path=/api/orders/**

        - id: inventory-service
          uri: lb://INVENTORY
          predicates:
            - Path=/api/inventory/**

        - id: product-service
          uri: lb://PRODUCT
          predicates:
            - Path=/api/products/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
