server:
  port: 9000

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true   # ensures services are lowercase
      routes:
        - id: order-service
          uri: lb://orders
          predicates:
            - Path=/api/orders/**
        - id: inventory-service
          uri: lb://inventory
          predicates:
            - Path=/api/inventory/**
        - id: product-service
          uri: lb://product
          predicates:
            - Path=/api/products/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

management:
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans
