resilience4j:
    retry:
        instances:
            inventoryRetry:
                maxRetryAttempts: 3
                waitDuration: 5s

    ratelimiter:
        instances:
            inventoryRateLimiter:
                limitForPeriod: 1
                limitRefreshPeriod: 5s
                timeoutDuration: 1s