spring:
  kafka:
    consumer:
      bootstrap-servers: localhost:9092
      group-id: inventory-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"
        spring.json.use.type.headers: false   # 🚨 ignore __TypeId__ header
        spring.json.value.default.type: com.microservices.inventory.dto.ProductCreatedEvent
