server:
  port: 8888   # Config Server default port

spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/sudeep776/InventoryManagementConfig
          default-label: main   # replace with your branch name if not main
          clone-on-start: true

      # DO NOT set bootstrap=true here for server
      fail-fast: true   # fail quickly if repo not found
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
